# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=30, verbose_name='活动标题')),
                ('message', models.TextField(blank=True, verbose_name='签到内容')),
            ],
            options={
                'verbose_name': '活动',
            },
        ),
        migrations.CreateModel(
            name='ContactSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.CharField(db_index=True, max_length=30, verbose_name='嘉宾')),
                ('seat', models.CharField(max_length=64, verbose_name='座位')),
                ('is_sign', models.BooleanField(default=False, editable=False, verbose_name='签到')),
                ('createtime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('active', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active', to='app.Active')),
            ],
            options={
                'verbose_name': '嘉宾座位',
            },
        ),
    ]
