# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='active',
            name='message',
        ),
        migrations.AlterField(
            model_name='contactseat',
            name='active',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active', to='app.Active', verbose_name='活动'),
        ),
    ]
